vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true

vim.g.autoformat = true

local opt = vim.opt
opt.number = true             -- Show line numbers
opt.relativenumber = true     -- Relative line numbers
opt.clipboard = "unnamedplus"   -- Use system clipboard
opt.splitright = true         -- Vertical splits to the right
opt.splitbelow = true         -- Horizontal splits below
opt.undofile = true           -- Enable persistent undo
opt.ignorecase = true         -- Case insensitive searching
opt.smartcase = true          -- Case-sensitive if uppercase present
opt.mouse = "a"               -- Enable mouse support
opt.cursorline = true         -- Highlight the current line
opt.termguicolors = true      -- True color support
opt.signcolumn = "yes"        -- Always show signcolumn
opt.scrolloff = 8             -- Keep at least 8 lines above/below cursor
opt.updatetime = 250          -- Faster completion / diagnostic response
opt.expandtab = true 
opt.cursorline = true
opt.foldlevel = 99
opt.foldmethod = "indent"
opt.foldtext = ""
opt.formatexpr = "v:lua.LazyVim.format.formatexpr()"
opt.formatoptions = "jcroqlnt" -- tcqj
opt.grepformat = "%f:%l:%c:%m"
opt.grepprg = "rg --vimgrep"
opt.timeoutlen = vim.g.vscode and 1000 or 300 -- Lower than default (1000) to quickly trigger which-key
opt.undofile = true
opt.undolevels = 10000
opt.updatetime = 200 -- Save swap file and trigger CursorHold
opt.virtualedit = "block" -- Allow cursor to move where there is no text in visual block mode
opt.wildmode = "longest:full,full" -- Command-line completion mode
